name: Build and Test C++ Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make valgrind

      - name: Build ex00
        working-directory: cpp_00/ex00
        run: |
          echo "Testing Makefile..."
          make
          echo "Cleaning and relinking..."
          make clean
          make
          echo "Testing re..."
          make re

      - name: Run tests for ex00
        if: success()
        working-directory: cpp_00/ex00
        run: |
            echo "TODO: Implement tests for ex00"

      - name: Build and test ex01
        if: success()
        working-directory: cpp_00/ex01
        run: |
            echo "TODO: Implement tests for ex01"

      - name: Build and test ex02
        if: success()
        working-directory: cpp_00/ex02
        run: |
            echo "TODO: Implement tests for ex02"
