name: Build and Test C++ Project

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make valgrind

      - name: Run test scripts
        run: |
          artifact_log="failed_tests.txt"
          echo "" > $artifact_log
          echo "success" > build_status.txt

          for script in $(find . -name "test_*.sh"); do
            echo "Running $script"
            dir=$(dirname "$script")
            cd $dir
            
            bash $(basename "$script")
            
            if [ -f debug.txt ]; then
              echo "$(basename $dir): Test failed." >> ../../$artifact_log
            fi

            cd - > /dev/null
          done

          if [ -s $artifact_log ]; then
            echo "Some tests failed. See $artifact_log for details."
            echo "failure" > build_status.txt
          else
            echo "All tests passed successfully."
          fi

      - name: Upload artifact if tests failed
        uses: actions/upload-artifact@v4
        with:
          name: failed-tests
          path: failed_tests.txt

      - name: Upload build status
        uses: actions/upload-artifact@v4
        with:
          name: build-status
          path: build_status.txt

  post:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build status
        uses: actions/download-artifact@v4
        with:
          name: build-status
          path: .

      - name: Read build status
        id: read_status
        run: |
          STATUS=$(cat build_status.txt)
          echo "::set-output name=status::$STATUS"

      - name: Set up Git identity
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

      - name: Configure GitHub authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Push to main on success
        if: ${{ steps.read_status.outputs.status == 'success' }}
        run: |
          git fetch origin main || echo "Branch 'main' does not exist. It will be created."
          git checkout main || git checkout -b main
          git merge develop --allow-unrelated-histories --strategy-option theirs
          git push origin main

      - name: Sync develop with main
        if: ${{ steps.read_status.outputs.status == 'success' }}
        run: |
          git checkout develop
          git merge main || git rebase main
          git push origin develop

      - name: Push to debug on failure
        if: ${{ steps.read_status.outputs.status == 'failure' }}
        run: |
          git checkout -b debug || git checkout debug
          git add .
          git commit -m "Debugging branch: Fix failed tests"
          git push origin debug
