name: Build and Test C++ Project

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make valgrind

      - name: Test cpp_00/ex00
        working-directory: cpp_00/ex00
        run: |
          echo "Testing Makefile for ex00"
          make
          echo "Cleaning and relinking..."
          make clean
          make
          echo "Testing re..."
          make re
          echo "TODO: Implement tests for ex00"

      - name: Test cpp_00/ex01
        working-directory: cpp_00/ex01
        run: |
          echo "Testing Makefile for ex01"
          make
          echo "Cleaning and relinking..."
          make clean
          make
          echo "Testing re..."
          make re
          echo "TODO: Implement tests for ex01"

      - name: Test cpp_00/ex02
        working-directory: cpp_00/ex02
        run: |
          echo "Testing Makefile for ex02"
          make
          echo "Cleaning and relinking..."
          make clean
          make
          echo "Testing re..."
          make re
          echo "TODO: Implement tests for ex02"
