name: Restrict PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" != "main" || "${{ github.event.pull_request.head.ref }}" != "develop" ]]; then
            echo -e "\033[1;31mOnly pull requests from 'develop' to 'main' are allowed.\033[0m"
            exit 1
          fi
        shell: bash
