name: Develop Branch Workflow

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make valgrind

      - name: Run test scripts
        run: |
          failed=false

          for script in $(find . -name "test_m0*ex*.sh"); do
            echo "\033[1;33mRunning $script\033[0m"
            dir=$(dirname "$script")
            cd $dir

            bash $(basename "$script")

            if [ -f debug.txt ]; then
              echo "$(basename $dir): Test failed." >> ../failed_tests.txt
              failed=true
            fi

            cd - > /dev/null
          done

          if [ "$failed" = true ]; then
            echo "\n\033[1;31mTests failed. See failed_tests.txt for details.\033[0m"
            echo "failure" > build_status.txt
          else
            echo "\n\033[1;32mAll tests passed successfully.\033[0m"
            echo "success" > build_status.txt
          fi

      - name: Upload build status and failed tests log
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build_status.txt
            failed_tests.txt
          if-no-files-found: ignore

  redirect-or-push:
    needs: run-tests
    runs-on: ubuntu-24.04
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build status
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Check build status
        id: check_status
        run: |
          STATUS=$(cat build_status.txt)
          echo "::set-output name=status::$STATUS"

      - name: Redirect push to debug
        if: steps.check_status.outputs.status == 'failure'
        run: |
          git fetch origin debug || echo "\033[1;33mBranch 'debug' does not exist.\033[0m"
          if ! git ls-remote --exit-code origin debug; then
            git branch debug
            echo "\033[1;36mBranch 'debug' created.\033[0m"
          fi

          git checkout debug
          git merge develop --allow-unrelated-histories --strategy-option theirs
          git push origin debug

      - name: Authorize push to develop
        if: steps.check_status.outputs.status == 'success'
        run: |
          echo "\033[1;32mTests passed. Push to 'develop' is allowed.\033[0m"
