name: Tests and Pull Requests

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make valgrind

      - name: Run test scripts
        run: |
          artifact_log="failed_tests.txt"
          echo "" > $artifact_log

          for script in $(find . -name "test_m0*ex*.sh"); do
            echo "Running $script"
            dir=$(dirname "$script")
            cd $dir

            bash $(basename "$script")

            if [ -f debug.txt ]; then
              echo "$(basename $script): FAILED" >> ../../$artifact_log
            fi

            cd - > /dev/null
          done

          if [ -s $artifact_log ]; then
            echo "Some tests failed. See $artifact_log for details."
            exit 1
          else
            echo "All tests passed successfully."
          fi

      - name: Upload failed tests log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-tests
          path: failed_tests.txt
